# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: print_debug 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "print_debug"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Wayne Conrad"]
  s.date = "2014-08-29"
  s.description = "Write debug output to stderr.  Optionally print the source filename and line number, or the source of the debug statement.  Easily print debug from the middle of call chains.  This is for those who prefer to debug by writing things to the console.  Since it writes to stderr, it's more useful than Kernel#p when working with a program that is run with stdout redirection.  Output goes to $stderr by default, but that's configurable."
  s.email = "wconrad@yagni.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "Rakefile",
    "VERSION",
    "lib/print_debug.rb",
    "spec/print_debug_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/wconrad/print_debug"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "print debug to stderr, with flair"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.7"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<rake>, ["~> 10.3"])
      s.add_development_dependency(%q<redcarpet>, ["~> 3.1"])
      s.add_development_dependency(%q<rspec>, ["~> 3.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.8.7"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.7"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<rake>, ["~> 10.3"])
      s.add_dependency(%q<redcarpet>, ["~> 3.1"])
      s.add_dependency(%q<rspec>, ["~> 3.0"])
      s.add_dependency(%q<yard>, ["~> 0.8.7"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.7"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<rake>, ["~> 10.3"])
    s.add_dependency(%q<redcarpet>, ["~> 3.1"])
    s.add_dependency(%q<rspec>, ["~> 3.0"])
    s.add_dependency(%q<yard>, ["~> 0.8.7"])
  end
end

